import type { Language } from '../../data/content';

export interface AuthUser {
  id: string;
  name: string;
  email: string;
  createdAt: string;
}

export const authUi = {
  ja: {
    loginNav: 'ログイン',
    logout: 'ログアウト',
    signedInAs: 'ログイン中',
    eyebrow: 'DEEP PLATE · ACCOUNT',
    title: '保存した好みを、次の画面でも続ける',
    body: 'アカウントにログインすると、保存したレストランを引き継げます。',
    loginMode: 'ログイン',
    registerMode: '新規登録',
    nameLabel: 'お名前',
    namePlaceholder: '例：Yuki',
    emailLabel: 'メールアドレス',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'パスワード',
    passwordPlaceholder: '8文字以上',
    submit: 'ログイン',
    registerSubmit: 'アカウントを作成',
    submitting: '接続中…',
    requiredError: 'すべての項目を入力してください。',
    emailError: 'メールアドレスの形式を確認してください。',
    passwordError: 'パスワードは8文字以上で入力してください。',
    serverError: 'サーバーに接続できませんでした。もう一度お試しください。',
    privacy: 'このブラウザにはログイントークンのみ保存し、パスワードは保存しません。',
    saveRequired: '保存機能はログイン後に利用できます。ログイン後、この画面に戻ります。',
    paymentRequired: '注文の確認にはログインが必要です。ログイン後、決済の画面に戻ります。',
    back: 'レストランを見る',
  },
  ko: {
    loginNav: '로그인',
    logout: '로그아웃',
    signedInAs: '로그인 중',
    eyebrow: 'DEEP PLATE · ACCOUNT',
    title: '저장한 취향을, 다음 화면에서도 이어가기',
    body: '계정으로 로그인하면 저장한 맛집을 이어서 확인할 수 있습니다.',
    loginMode: '로그인',
    registerMode: '회원가입',
    nameLabel: '이름',
    namePlaceholder: '예: 성진',
    emailLabel: '이메일',
    emailPlaceholder: 'you@example.com',
    passwordLabel: '비밀번호',
    passwordPlaceholder: '8자 이상',
    submit: '로그인',
    registerSubmit: '계정 만들기',
    submitting: '연결 중…',
    requiredError: '모든 항목을 입력해 주세요.',
    emailError: '이메일 형식을 확인해 주세요.',
    passwordError: '비밀번호는 8자 이상 입력해 주세요.',
    serverError: '서버에 연결하지 못했습니다. 다시 시도해 주세요.',
    privacy: '이 브라우저에는 로그인 토큰만 저장하며 비밀번호는 저장하지 않습니다.',
    saveRequired: '저장 기능은 로그인 후 이용할 수 있습니다. 로그인하면 원래 화면으로 돌아갑니다.',
    paymentRequired: '주문 확인을 위해 로그인해 주세요. 로그인 후 진행하던 결제 화면으로 돌아갑니다.',
    back: '맛집 둘러보기',
  },
  en: {
    loginNav: 'Log in',
    logout: 'Log out',
    signedInAs: 'Signed in',
    eyebrow: 'DEEP PLATE · ACCOUNT',
    title: 'Keep your saved tastes for the next screen',
    body: 'Log in to keep your saved restaurants connected to your account.',
    loginMode: 'Log in',
    registerMode: 'Create account',
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Alex',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'At least 8 characters',
    submit: 'Log in',
    registerSubmit: 'Create account',
    submitting: 'Connecting…',
    requiredError: 'Complete every field.',
    emailError: 'Check the email address format.',
    passwordError: 'Use at least 8 characters for the password.',
    serverError: 'Could not reach the server. Please try again.',
    privacy: 'Only the login token is stored in this browser. Your password is never stored.',
    saveRequired: 'Log in to save places. You will return to the previous screen after login.',
    paymentRequired: 'Log in to access your order. You will return to checkout after login.',
    back: 'Explore places',
  },
} satisfies Record<Language, Record<string, string>>;
